# Lab / Demo Inventory
all:
  vars:
    wazuh_manager_ip: "192.168.56.10"
    wazuh_manager_port: 1514
    wazuh_agent_version: "4.9.0"
    wazuh_registration_password: "lab-password-change-me"

  children:
    linux_servers:
      hosts:
        lab-ubuntu-01:
          ansible_host: 192.168.56.21
        lab-centos-01:
          ansible_host: 192.168.56.22

    windows_servers:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
      hosts:
        lab-win-01:
          ansible_host: 192.168.56.30
          ansible_user: vagrant
          ansible_password: vagrant

    docker_hosts:
      hosts:
        lab-docker-01:
          ansible_host: 192.168.56.40
